{"Database": "prodoperationaldb", "table": "user_dimension", "status": "19/02/14 05:13:48 [main]: ERROR SessionState: Status: Failed\n", "caused by": "Caused by: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {\"key\":{\"_col0\":{\"transactionid\":21994,\"bucketid\":0,\"rowid\":14},\"_col1\":\"GO\"},\"value\":{\"_col0\":1}}\n"}
